import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType } from 'docx';

export function buildJsonExport(prd, sections) {
  return {
    exportFormat: 'pm-ai-prd-v1',
    exportedAt: new Date().toISOString(),
    title: prd.title,
    status: prd.status,
    sections
  };
}

function sectionContent(s) {
  if (typeof s.content === 'string') return s.content;
  if (Array.isArray(s.content)) return s.content.join('\n');
  if (typeof s.content === 'object' && s.content !== null) return JSON.stringify(s.content, null, 2);
  return '';
}

export function buildMarkdown(title, sections) {
  let md = `# ${title}\n\n`;
  md += `> Status: draft · Generated by PM AI Tool · ${new Date().toLocaleDateString()}\n\n---\n\n`;

  for (const s of sections || []) {
    const num = s.num ? `${s.num} ` : '';
    md += `## ${num}${s.title || 'Section'}\n\n`;

    if (s.confidence) {
      md += `> Confidence: ${s.confidence}\n\n`;
    }

    if (s.type === 'list' && Array.isArray(s.items)) {
      for (const item of s.items) {
        if (typeof item === 'string') {
          md += `- ${item}\n`;
        } else if (typeof item === 'object' && item !== null) {
          const label = item.label || item.title || item.name || '';
          const desc = item.description || item.content || item.detail || '';
          if (label && desc) {
            md += `- **${label}**: ${desc}\n`;
          } else {
            md += `- ${label || desc || JSON.stringify(item)}\n`;
          }
        }
      }
      md += '\n';
    } else if (s.type === 'table' && s.rows) {
      const headers = s.headers || [];
      if (headers.length > 0) {
        md += '| ' + headers.join(' | ') + ' |\n';
        md += '|' + headers.map(() => ' --- ').join('|') + '|\n';
      }
      for (const row of s.rows || []) {
        const cells = Array.isArray(row) ? row : Object.values(row);
        md += '| ' + cells.map(c => String(c ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')).join(' | ') + ' |\n';
      }
      md += '\n';
    } else {
      const content = sectionContent(s);
      if (content) {
        md += `${content}\n\n`;
      }
    }
  }

  md += `---\n\n*PM AI Tool*\n`;
  return md;
}

function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function markdownToHtml(text) {
  if (!text) return '';
  let html = escapeHtml(text);
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');
  html = html.replace(/`(.+?)`/g, '<code>$1</code>');

  const lines = html.split('\n');
  const result = [];
  let inList = false;
  let listType = 'ul';

  for (const line of lines) {
    const trimmed = line.trim();
    if (/^[-*•]\s/.test(trimmed)) {
      if (!inList) { result.push('<ul>'); inList = true; listType = 'ul'; }
      result.push(`<li>${trimmed.replace(/^[-*•]\s+/, '')}</li>`);
    } else if (/^\d+\.\s/.test(trimmed)) {
      if (!inList) { result.push('<ol>'); inList = true; listType = 'ol'; }
      result.push(`<li>${trimmed.replace(/^\d+\.\s+/, '')}</li>`);
    } else {
      if (inList) {
        result.push(listType === 'ol' ? '</ol>' : '</ul>');
        inList = false;
      }
      if (/^####\s/.test(trimmed)) {
        result.push(`<h5>${trimmed.replace(/^####\s+/, '')}</h5>`);
      } else if (/^###\s/.test(trimmed)) {
        result.push(`<h4>${trimmed.replace(/^###\s+/, '')}</h4>`);
      } else if (/^##\s/.test(trimmed)) {
        result.push(`<h3>${trimmed.replace(/^##\s+/, '')}</h3>`);
      } else if (/^#\s/.test(trimmed)) {
        result.push(`<h2>${trimmed.replace(/^#\s+/, '')}</h2>`);
      } else if (trimmed === '') {
        result.push('');
      } else {
        result.push(`<p>${trimmed}</p>`);
      }
    }
  }
  if (inList) result.push(listType === 'ol' ? '</ol>' : '</ul>');
  return result.join('\n');
}

function renderSectionContent(s) {
  const parts = [];

  if (s.confidence) {
    parts.push(`<div class="confidence"><span class="confidence-badge">${escapeHtml(s.confidence)}</span></div>`);
  }

  if (s.type === 'list' && Array.isArray(s.items)) {
    parts.push('<ul class="feature-list">');
    for (const item of s.items) {
      if (typeof item === 'string') {
        parts.push(`<li>${markdownToHtml(item)}</li>`);
      } else if (typeof item === 'object' && item !== null) {
        const label = item.label || item.title || item.name || item.id || '';
        const desc = item.description || item.content || item.detail || '';
        if (label && desc) {
          parts.push(`<li><strong>${escapeHtml(label)}</strong>: ${markdownToHtml(desc)}</li>`);
        } else {
          parts.push(`<li>${markdownToHtml(label || desc || JSON.stringify(item))}</li>`);
        }
      }
    }
    parts.push('</ul>');
  } else if (s.type === 'table' && s.rows) {
    const headers = s.headers || [];
    parts.push('<div class="table-wrap"><table>');
    if (headers.length > 0) {
      parts.push('<thead><tr>' + headers.map(h => `<th>${escapeHtml(h)}</th>`).join('') + '</tr></thead>');
    }
    parts.push('<tbody>');
    for (const row of s.rows || []) {
      const cells = Array.isArray(row) ? row : Object.values(row);
      parts.push('<tr>' + cells.map(c => `<td>${escapeHtml(String(c ?? ''))}</td>`).join('') + '</tr>');
    }
    parts.push('</tbody></table></div>');
  } else {
    const content = sectionContent(s);
    if (content) {
      parts.push(markdownToHtml(content));
    }
  }

  return parts.join('\n');
}

export function buildHtmlDocument(prd, sections) {
  const secs = sections || [];
  const tocItems = secs.map((s, i) => {
    const num = s.num || String(i + 1).padStart(2, '0');
    const slug = `section-${i}`;
    return `<a href="#${slug}">${escapeHtml(num)} ${escapeHtml(s.title || 'Section')}</a>`;
  });

  const parts = [];
  parts.push(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${escapeHtml(prd.title)}</title>`);
  parts.push(`<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:'Inter',system-ui,-apple-system,sans-serif;max-width:820px;margin:0 auto;padding:40px 28px 60px;color:#1a1a2e;line-height:1.7;font-size:15px;background:#fff}
@media print{body{padding:20px;font-size:13px;line-height:1.5}}
h1{font-size:28px;font-weight:700;color:#0f0f23;border-bottom:3px solid #5B7EF8;padding-bottom:14px;margin-bottom:8px;letter-spacing:-0.5px}
.meta{color:#666;font-size:13px;margin-bottom:24px;padding-bottom:16px;border-bottom:1px solid #e8e8f0}
.toc{background:#f8f8fc;border:1px solid #e8e8f0;border-radius:10px;padding:20px 24px;margin-bottom:32px}
.toc h3{font-size:14px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:#5B7EF8;margin-bottom:12px}
.toc a{display:block;color:#3a3a5c;text-decoration:none;font-size:13px;padding:4px 0;transition:color .15s}
.toc a:hover{color:#5B7EF8}
h2{font-size:20px;font-weight:700;color:#0f0f23;margin-top:36px;margin-bottom:16px;padding-bottom:8px;border-bottom:2px solid #e8e8f0;letter-spacing:-0.3px}
h2 .num{color:#5B7EF8;font-weight:600}
h3{font-size:16px;font-weight:600;margin-top:20px;margin-bottom:8px;color:#2a2a4a}
h4{font-size:14px;font-weight:600;margin-top:16px;margin-bottom:6px;color:#3a3a5c}
h5{font-size:13px;font-weight:600;margin-top:12px;margin-bottom:4px;color:#4a4a6a}
p{margin-bottom:10px}
ul,ol{padding-left:24px;margin-bottom:12px}
li{margin-bottom:5px}
.feature-list li{margin-bottom:8px}
strong{font-weight:600;color:#0f0f23}
code{background:#f0f0f8;padding:1px 5px;border-radius:4px;font-size:0.88em;font-family:'SF Mono',Consolas,monospace}
.table-wrap{overflow-x:auto;margin:12px 0 16px}
table{border-collapse:collapse;width:100%;font-size:13px}
th{background:#f0f0f8;font-weight:600;text-align:left;padding:10px 12px;border:1px solid #ddd;color:#2a2a4a;font-size:12px;text-transform:uppercase;letter-spacing:0.3px}
td{padding:9px 12px;border:1px solid #ddd;vertical-align:top}
tr:nth-child(even) td{background:#fafafe}
.confidence{margin-bottom:10px}
.confidence-badge{display:inline-block;font-size:11px;font-weight:600;padding:2px 10px;border-radius:20px;background:#E8F5E9;color:#2E7D32;letter-spacing:0.3px}
hr{border:none;border-top:1px solid #e8e8f0;margin:28px 0}
.footer{text-align:center;font-size:11px;color:#999;margin-top:40px;padding-top:16px;border-top:1px solid #e8e8f0}
@media print{
  .toc{break-after:page}
  h2{break-before:auto;page-break-after:avoid}
  table{page-break-inside:avoid}
}
</style></head><body>`);

  parts.push(`<h1>${escapeHtml(prd.title)}</h1>`);
  parts.push(`<div class="meta">Status: ${escapeHtml(prd.status)} · Exported ${new Date().toLocaleString()}</div>`);

  if (tocItems.length > 3) {
    parts.push(`<nav class="toc"><h3>Table of Contents</h3>${tocItems.join('\n')}</nav>`);
  }

  for (let i = 0; i < secs.length; i++) {
    const s = secs[i];
    const num = s.num || String(i + 1).padStart(2, '0');
    const slug = `section-${i}`;
    parts.push(`<h2 id="${slug}"><span class="num">${escapeHtml(num)}</span> ${escapeHtml(s.title || 'Section')}</h2>`);
    parts.push(renderSectionContent(s));
  }

  parts.push('<div class="footer">PM AI Tool</div></body></html>');
  return parts.join('\n');
}

export async function buildDocxBuffer(title, sections) {
  const children = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `Status: draft · Generated by PM AI Tool · ${new Date().toLocaleDateString()}`, italics: true, size: 20, color: '666666' }),
      ],
      spacing: { after: 400 },
    }),
  ];

  for (const s of sections || []) {
    const num = s.num ? `${s.num} ` : '';
    children.push(
      new Paragraph({
        text: `${num}${s.title || 'Section'}`.trim(),
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 120 },
      })
    );

    if (s.confidence) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: `Confidence: ${s.confidence}`, italics: true, size: 18, color: '2E7D32' })],
          spacing: { after: 80 },
        })
      );
    }

    if (s.type === 'list' && Array.isArray(s.items)) {
      for (const item of s.items) {
        let text = '';
        if (typeof item === 'string') {
          text = item;
        } else if (typeof item === 'object' && item !== null) {
          const label = item.label || item.title || item.name || '';
          const desc = item.description || item.content || item.detail || '';
          text = label && desc ? `${label}: ${desc}` : (label || desc || JSON.stringify(item));
        }
        children.push(
          new Paragraph({
            children: [new TextRun({ text: `• ${text}` })],
            spacing: { after: 60 },
            indent: { left: 360 },
          })
        );
      }
    } else if (s.type === 'table' && s.rows && s.headers) {
      const headers = s.headers || [];
      const tableRows = [];
      if (headers.length > 0) {
        tableRows.push(
          new TableRow({
            children: headers.map(h =>
              new TableCell({
                children: [new Paragraph({ children: [new TextRun({ text: String(h), bold: true, size: 18 })] })],
                width: { size: Math.floor(9000 / headers.length), type: WidthType.DXA },
                shading: { fill: 'F0F0F8' },
              })
            ),
          })
        );
      }
      for (const row of s.rows || []) {
        const cells = Array.isArray(row) ? row : Object.values(row);
        tableRows.push(
          new TableRow({
            children: cells.map(c =>
              new TableCell({
                children: [new Paragraph({ children: [new TextRun({ text: String(c ?? ''), size: 18 })] })],
                width: { size: Math.floor(9000 / Math.max(cells.length, 1)), type: WidthType.DXA },
              })
            ),
          })
        );
      }
      if (tableRows.length > 0) {
        children.push(
          new Table({
            rows: tableRows,
            width: { size: 9000, type: WidthType.DXA },
          })
        );
        children.push(new Paragraph({ spacing: { after: 120 } }));
      }
    } else {
      const content = sectionContent(s);
      if (content) {
        const paras = content.split('\n').filter(l => l.trim());
        for (const p of paras) {
          const runs = [];
          const parts = p.split(/(\*\*[^*]+\*\*)/g);
          for (const part of parts) {
            if (part.startsWith('**') && part.endsWith('**')) {
              runs.push(new TextRun({ text: part.slice(2, -2), bold: true }));
            } else {
              runs.push(new TextRun(part));
            }
          }
          children.push(
            new Paragraph({ children: runs, spacing: { after: 80 } })
          );
        }
      }
    }
  }

  const doc = new Document({ sections: [{ children }] });
  return Packer.toBuffer(doc);
}
